---
title: "5. Multipoints and predictions"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

<!---

```{r setup}
library(biPOD)
```

This vignette will mainly revolve around the prediction of the so called "relapse time", i.e. the time in which the population we are modelling will reach a certain threshold value. If you consider some example, the usefulness of this procedure becomes evident. Let's suppose that we are modelling the growth/shrinkage of a tumor mass; with such procedure we might be able to infer at which instant of time the tumor will relapse/disappear. 

Let's first simulate an exponential growth

```{r}
T <- 3
time_steps <- 12
delta_t <- T / time_steps
n0 <- 1000
d <- biPOD::sim_stochastic_exponential(n0, .8, .2, steps = time_steps, delta_t = delta_t)
```

Now, we might be interested in understanding, for example, when the population will reach, for example, a size 10 times bigger than the other. Moreover, we want to look at how the prediction can become more and more accurate as the number of data points we have grows. Hence, let's first use only 25% of the points.

```{r}
n_points_to_use <- as.integer(0.25 * nrow(d))
partial_d <- d[1:n_points_to_use,]

x25 <- biPOD::init(partial_d, "sample.25")
x25 <- biPOD::fit(x25)
```

We can then plot the fit along with the distribution of the relapse time. We do also plot the unused points for the fit.

```{r, warning=FALSE}
fit.plot <- biPOD::plot_fit(x25, final_time = T * 1.01)
# Add the unused points
unused_data <- d[n_points_to_use + 1:nrow(d),] %>% na.omit()
fit.plot <- fit.plot + ggplot2::geom_point(unused_data, mapping=ggplot2::aes(x=time, y=count), alpha = .2)
times.plot <- biPOD::plot_relapse_time_distribution(x25, n0 * 10) + 
  ggplot2::scale_x_continuous(limits = c(2,6))
plots.25 <- ggpubr::ggarrange(plotlist = list(fit.plot, times.plot))
plots.25
```

We can now increase the number of points up to 50% of the total:

```{r, warning=FALSE, message=FALSE}
n_points_to_use <- as.integer(0.50 * nrow(d))
partial_d <- d[1:n_points_to_use,]

x50 <- biPOD::init(partial_d, "sample.50")
x50 <- biPOD::fit(x50)
```

```{r, warning=FALSE}
fit.plot <- biPOD::plot_fit(x50)
# Add the unused points
unused_data <- d[n_points_to_use + 1:nrow(d),] %>% na.omit()
fit.plot <- fit.plot + ggplot2::geom_point(unused_data, mapping=ggplot2::aes(x=time, y=count), alpha = .2)
times.plot <- biPOD::plot_relapse_time_distribution(x50, n0 * 10) +
  ggplot2::scale_x_continuous(limits = c(2,6))
plots.50 <- ggpubr::ggarrange(plotlist = list(fit.plot, times.plot))
plots.50
```

And we can finally use all the points:

```{r, warning=FALSE, message=FALSE}
n_points_to_use <- as.integer(1 * nrow(d))
partial_d <- d[1:n_points_to_use,]

x100 <- biPOD::init(partial_d, "sample.100")
x100 <- biPOD::fit(x100)
```

```{r, warning=FALSE}
fit.plot <- biPOD::plot_fit(x100, final_time = T * 1.01)
times.plot <- biPOD::plot_relapse_time_distribution(x100,  n0 * 10) +
  ggplot2::scale_x_continuous(limits = c(2,6))
plots.100 <- ggpubr::ggarrange(plotlist = list(fit.plot, times.plot))
plots.100
```

We can look at the summary of the three different runs:

```{r}
summary.plot <- ggpubr::ggarrange(plotlist = list(plots.25, plots.50, plots.100), labels = c("25%", "50%", "100%"), ncol = 1)
summary.plot <- cowplot::plot_grid(plotlist = list(plots.25, plots.50, plots.100), ncol = 1)
summary.plot
```

-->
