
#' Plot parameter posterior distributions
#'
#' Plots posterior densities for specified parameters from MCMC draws.
#'
#' @param fit_draws A list of chains, where each chain is a named list of parameter draws.
#' @param params Character vector of parameters (or regex patterns) to extract.
#' @param faceted Logical; whether to facet the plot by parameter (default `TRUE`).
#'
#' @return A `ggplot` object showing posterior densities for the selected parameters.
#' @examples
#' \dontrun{
#'   plot_parameter_posteriors(fit$draws, params = c("rho[1]", "K"))
#' }
#'
#' @export
plot_parameter_posteriors <- function(fit_draws, params, faceted = TRUE, colors = NULL) {

  chains <- fit_draws
  if (!is.list(chains)) stop("fit_draws must be a list of chains.")

  extract_params <- function(chain) {
    param_names <- names(chain)
    matched <- unique(unlist(lapply(params, function(p) if (p %in% param_names) p else grep(p, param_names, value = TRUE))))
    if (length(matched) == 0) stop(sprintf("No parameters matching '%s' found.", paste(params, collapse = ", ")))
    param_mat <- sapply(matched, function(p) unlist(chain[[p]]))
    if (is.null(dim(param_mat))) param_mat <- matrix(param_mat, ncol = length(matched))
    colnames(param_mat) <- matched
    as.data.frame(param_mat)
  }

  chain_dfs <- lapply(chains, extract_params)
  draws_df <- dplyr::bind_rows(chain_dfs, .id = "chain") %>%
    dplyr::mutate(iter = stats::ave(rep(1, n()), chain, FUN = seq_along))

  draws_long <- draws_df %>% tidyr::pivot_longer(-c(chain, iter), names_to = "parameter", values_to = "value")

  if (is.null(colors)) {
    colors = get_group_colors()
  }

  p <- ggplot2::ggplot(draws_long, ggplot2::aes(x = value, fill = parameter)) +
    ggplot2::geom_density(alpha = 0.7) +
    ggplot2::labs(x = "Value", y = "Density", fill = "Parameter") +
    ggplot2::theme_bw() +
    ggplot2::scale_fill_manual(values = colors)

  if (faceted) {
    p <- p + ggplot2::facet_wrap(~parameter, scales = "free", ncol = 2) +
      ggplot2::theme(legend.position = "none")
  }
  p
}

#' Plot MCMC trace plots for parameters
#'
#' Generates trace plots for parameters in an MCMC fit.
#'
#' @param fit A fitted model object containing posterior draws in `fit$draws`.
#'
#' @return A trace plot generated by `bayesplot::mcmc_trace`.
#' @examples
#' \dontrun{
#'   plot_trace_parameters(fit)
#' }
#'
#' @export
plot_trace_parameters <- function(fit, params = NULL) {
  draws_df <- posterior::as_draws_df(fit$draws())
  if (!is.null(params)) draws_df <- posterior::subset_draws(draws_df, variable = params)
  bayesplot::mcmc_trace(draws_df)
}
