# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

birthDeathLike_log <- function(m, n, delta_t, lambda, mu, pstream__ = 0L) {
    .Call(`_biPOD_birthDeathLike_log`, m, n, delta_t, lambda, mu, pstream__)
}

birthDeathLike_rng <- function(n, delta_t, lambda, mu, base_rng__, pstream__ = 0L) {
    .Call(`_biPOD_birthDeathLike_rng`, n, delta_t, lambda, mu, base_rng__, pstream__)
}

