# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("exact_fixed_all", "exact_fixed_birth", "exact_fixed_death", "exact_fixed_none", "gauss_fixed_all", "gauss_fixed_birth", "gauss_fixed_death", "gauss_fixed_none")

# load each stan module
Rcpp::loadModule("stan_fit4exact_fixed_all_mod", what = TRUE)
Rcpp::loadModule("stan_fit4exact_fixed_birth_mod", what = TRUE)
Rcpp::loadModule("stan_fit4exact_fixed_death_mod", what = TRUE)
Rcpp::loadModule("stan_fit4exact_fixed_none_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gauss_fixed_all_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gauss_fixed_birth_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gauss_fixed_death_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gauss_fixed_none_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
})
